apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  source:
    repoURL: https://github.com/dhpup/rollouts-multi.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  syncPolicy:
    automated: {}
